/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useFrame } from '@react-three/fiber';
import { useGLTF } from "@react-three/drei";
import { Camera, MeshStandardMaterial, Vector3 } from "three";

export default function Model(props) {
  const group = useRef();

  const [rotations, setRotations] = useState({ x: 0, y: 0, z: 0 });
  const [ypos, setYpos] = useState(0);
  const [mousepos, setMousepos] = useState({ x: 0, y: 0 });

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    setRotations({
      x: -Math.PI / 12 + Math.cos(t / 2) * 5,
      y: Math.sin(t / 2) * 10,
      z: (1 + Math.sin(t / 1.5)) * 1
    });

    setMousepos({ x: state.mouse.x, y: state.mouse.y });
    //console.log(vector);

    //rotations.x = -Math.PI / 12 + Math.cos(t / 2) / 8
    //rotations.y = Math.sin(t / 2) / 8 - (props.rotOffset || 0)
    //rotations.z = (1 + Math.sin(t / 1.5)) / (props.variation * 15 || 20)
    rotations.z += 0.3;
    rotations.y += 0.5;
    rotations.x += 0.2;
    //setRotations(rotations);

    setYpos((1 + Math.sin(t / 1.5)) / 10);
  });

  function getLetterPos(x, y, z) {
    return [x, y, z];
  }

  var model = "/lettercube.glb";
  var { nodes } = useGLTF(model);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={ nodes.Cube.geometry }
        material={nodes.Cube.material}
        position={getLetterPos(-1.5, 0.8 + ypos * 0.3, 0)}
        rotation={[0 + rotations.x * Math.PI / 180, (25 - rotations.y) * Math.PI / 180, 0 + rotations.z * Math.PI / 180]}
        scale={[0.5, 0.5, 0.5]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={ nodes.Cube.geometry }
        material={nodes.Cube.material}
        position={getLetterPos(1.0, 0.3 + ypos * 0.3, 0.5)}
        rotation={[15 + rotations.x * Math.PI / 180, (25 - rotations.y) * Math.PI / 180, 50 + rotations.z * Math.PI / 180]}
        scale={[0.5, 0.5, 0.5]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={ nodes.Cube.geometry }
        material={nodes.Cube.material}
        position={getLetterPos(0.0, 0.5 + ypos * 0.3, -0.8)}
        rotation={[75 + rotations.x * Math.PI / 180, (25 - rotations.y) * Math.PI / 180, 50 + rotations.z * Math.PI / 180]}
        scale={[0.5, 0.5, 0.5]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={ nodes.Cube.geometry }
        material={nodes.Cube.material}
        position={getLetterPos(3.0, 0.0 + ypos * 0.3, -0.4)}
        rotation={[11 + rotations.x * Math.PI / 180, (25 + rotations.y) * Math.PI / 180, 15 + rotations.z * Math.PI / 180]}
        scale={[0.5, 0.5, 0.5]}
      />
    </group>
  );
}

//useGLTF.preload("/LLetter.glb");